---
title: "Occurrence Data Entry Protocol"
author: "Emma Menchions"
date: "`r Sys.Date()`"
output: html_document
---

# Data Entry

## Template

*Start new template for every field journal.*

-   Copy and paste the template "HJ-occ-entry-template.xlsx"

-   Rename to "HJ-[input archiveID]-occ-entry-[YY-MM-DD].xlsx"

## Setting up

1.  Open the data entry excel sheet

2.  Open the field journal to the first page

3.  Open two internet search windows

4.  In the first window --\> [https://www.inaturalist.org](https://www.inaturalist.org/home)

    -   click "Explore" tab

    -   zoom in on south western BC

    -   click the red rectangular select button

    -   click and drag to select an area that extends from around Hope BC to the east, encompasses all of Vancouver Island, and goes down to Seattle/ Tacoma in the south

    -   set this window aside and return to excel sheet

5.  Second window will be used to search up localities that you are uncertain of

## Entering data

Begin with the **first page in a journal.**

1.  Enter "**pageNum"** (page number) --\> e.g 1 . (circled in bottom corner of pages)

2.  **Scan the page for observations (species names)** starting at the top of the page. All species names are acceptable, except for entries which have a collection number beside them (or say "coll" indicating a collection).

    -   This could be in a **set of species names observed at a particular location** (with no collection numbers)

    -   **OR the name of a species in the description of a collected specimen** - in this case, just make sure that if there are multiple collected specimens from that location, that one of these associated species was not collected. If it was, do not include it as an observation in a row. The occurrence of this species would be documented in the herbarium and uploaded to GBIF.

    -   To look for what location and date information is associated with each name, he often put the location and a date and then species associated with it BELOW or BESIDE

3.  Enter "**numPage"** **[REQUIRED]** (number on page) as the number of the observation on the page (e.g. the first species name that matches the criteria in step 3 gets"1", the next one "2", etc.)

    -   easiest to enter all of the other data for the observation sequentially on the page and then click and drag a sequence of numbers in excel to number each observation

    -   enter observations by columns (e.g. if there are two columns of names on a page, enter the first column and then the second)

4.  **"vName"** **[REQUIRED]** = the verbatim name written in the notes

    -   this may be an abbreviation (e.g. Stel med)

    -   or full species name (could be misspelled, include these spelling mistakes)

    -   or a full species name which is outdated, keep this outdated name, we want to know exactly what he wrote so we can be confident in assigning an updates species name

5.  **"vSciName" [REQUIRED]** = your estimation of what the full species name is

    -   This is where iNaturalist is helpful. Often the taxonomy might be outdated (indicated by a bracketed name in the search results on iNat).

        -   start entering first 3 letters of generic name and species name

        -   see if it occurs in the region

        -   keep trying with different letters to find best match

        -   if there are multiple species possible and/ or you can't decipher the name, place a note in the "dataEntryRemarks" column (e.g. "could not decipher taxon name")

        -   Once you are reasonably certain of a full name, start typing it into search bar and finish typing by looking at the result. If the result still pops up then its proper spelling and you can copy it to spreadsheet

        -   If it is an outdated name, it will often be bracketed beside another name for the same species in the iNaturalist search, can use this as a spelling guide as well

    -   Enter your best guess of what the full verbatim name was meant to be

    -   there should be no spelling mistakes, but outdated taxon names should still be used here

6.  **"Conf"** **[REQUIRED]** = enter your confidence level in the **taxon name** estimate (low = l, medium = m, high = h)

    -   the names with low confidence will be checked over once all of the occurrences have been entered

    -   entries with medium confidence may be returned to if there is time

7.  **"sciName" [REQUIRED] =** **full, properly spelled, updated taxon names.**

    -   refer to iNaturalist for updates taxon names

    -   If subspecies or variety, just include this epithet, and do not include the "ssp." or "var." abbreviations. (e.g. Instead of Lupinus latifolius ssp. subalpinus, put "Lupinus latifolius subalpinus")

8.  **"date" [REQUIRED] =** fill in YYYYMMDD

9.  **"locality" [REQUIRED] =** string describing specific location. Does not contain country, province information, but includes place name (island, town, city, area, landmark, trail, road) or position relative to to these features. **Go from GENERAL to SPECIFIC and separate names with ";"**. If there are any words you can't make out or are uncertain of, use [brackets] around the estimated word. I*mportant: Use a web search to make ensure entry of proper spelling of place name!*

    **USE CAPITAL LETTERS** for each word of city/ town/ municipality/ island names

    **SPELL OUT ABBREVIATIONS**

    -   e.g. Mt --\> Mount, Rd --\> Rd

    **SEPARATE PLACE NAMES WITH SEMI-COLON**. Do not tack on terms like "area" .

    e.g. "George Hill area" --\> "George Hill; area around George Hill"

    Start with island/ town/ area name...

    -   e.g. "Mt. Sutil, Galiano" becomes --\> "Galiano Island; Mount Sutil"

    -   e.g. "Magic lake horse padoc" becomes --\> "North Pender Island; Magic Lake; Magic Lake horse padoc"

    -   e.g. "fen below Magic Lake" becomes --\> "North Pender Island; Magic Lake; fen below lake"

    -   e.g. "small island S of prevost island" --\> "Prevost Island; small island to south"

    -   e.g. "north side of Cowichan Lake" becomes --\> "Cowichan; Cowichan Lake; north side of lake"

    -   If there is a string of words like 10 km north of Mount Suitl

        -   e.g. Galiano Island; Mount Sutil; 10 kilometers north of Mt. Sutil

10. **"Country" [REQUIRED] =** full name of country of collection (either Canada or United States of America)

11. **"stateProvince" [REQUIRED] =** Full name of province/ state of collection (either British Columbia or Washington)

12. **"island" [REQUIRED] =** full name of island (if collected on island)

    -   e.g. Galiano Island or Saltspring Island

    -   must contain the word "Island" capitalized

13. **"idQualifier" =** identification Qualifier.

    -   only fill out if there was a question mark or other note of uncertainty about the taxon identification from HJ

    -   basically replacing question marks and brackets with more formal annotations of uncertainty in ID

        -   e.g. Festuca (?) rubra or Festuca (rubra) --\> enter here as Festuca cf. rubra

        -   e.g. Festuca sp ? --\> enter here as Festuca cf. sp

        -   e.g Festuca rubra --\> enter here as cf. Festuca rubra

14. **"county" =** only fill out if on Vancouver Island or Mainland (otherwise it will be assigned depending on the island that it is on)

15. **"occStatus" =** occurrence status (either present of absent)

    -   to save time, only enter if there is a note clearly saying "absent" or a species name is crossed out when there is a list of species with no other species name pointed to (indicating an absence and not just a name update)

        -   then enter the word "absent"

    -   otherwise, assume the species was observed (present) and you do not need to fill this in

16. **"habitat" =** string describing the habitat conditions

    -   you can use commas when listing things

    -   to start a new sentence use a semicolon ";" rather than a period

    -   descriptions about type of species growing in area, but do not list associate species, this will be done in the associated taxa and occurrences columns

    -   If there are any words you can't make out or are uncertain of, use [brackets]? around the estimated word

        -   e.g. "Quercus woodland",

        -   e.g. "vernal seepage in limestone rock outcropping"

        -   e.g. "edges of lake"

        -   e.g. "floating in lake"

        -   e.g. "ditch"

        -   e.g. "aquatic"

        -   e.g. "bog"

        -   e.g. "marsh"

        -   e.g. "[intertidal]? marsh

    -   For forest type codes like Cw, Fd, write out the full species names: <https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/tree-seed/tree-seed-centre/seed-testing/codes>

17. **"assCollTaxa"** = associated collected taxa (names of associated species), growing at same locality at same time

    -   ONLY denote associated taxa names in this field, if there is a record of a specimen collection (either a collection number or a note about "coll" next to a species name) since these won't be included later but are stored in a separate database (herbarium)

    -   e.g. Stellaria media 2678 --\> "Stellaria media"

    -   use updated and full names of these taxa

    -   use iNaturalist to decipher names/ abbreviations of associated taxa and for updated names

    -   if you can't decipher a name, place the estimated name in [brackets] and make a note in the "dataEntryRemarks" column (e.g. cannot decipher one or more associated species names"

    -   enter multiple names separated by commas

18. **"assCollOcc"** = associated collected occurrences

    -   the collection numbers associated with associated collected occurrences
    -   enter multiple numbers separated by commas

19. **"locationRemarks" =** additional information about location. Separate sentences with semicolons

    Anything pertaining to the general location and not what has already been said in the habitat field. If there are any words you can't make out or are uncertain of, use [brackets] around the estimated word

    -   e.g. "poly 15" (indicating geographic polygon for surveys)

    -   e.g. "slope 15 percent; aspect 240 degrees" (try to spell out degrees and percents)

    -   e.g. "mostly open water in lake"

20. **"vTaxonRank"** **[REQUIRED]** = The most specific level of taxonomy provided verbatim. Only use if the verbatim taxon name is a family name or higher. If genus, species or subspecies, then this information will be filled in later automatically

    -   e.g. if "Brassicaceae" --\> put "family"

21. **"vElevM" = verbatim elevation in meters.** If there is any information about elevation of the site, input into this column, WITHOUT units. It seems like all of HJ's measurements were in meters. On the off chance that they're not, convert to meters before entering.

22. **"vLat" & "vLon" =** verbatim latitude and longitude.

    For some locations, HJ provided coordinate infromation in lat, long coordinates. If this is the case input this info here either as:

    1.  decimal degrees --\> e.g vLat = "45.678"

    2.  degrees, minuntes, seconds --\> e.g. "45 67 89" (do not include " symbols)

    Everything will be converted to decimal degrees at a later stage.

23. **"vUTM" =** verbatim UTM coordinates. If provided, enter in the format:

    -   "10U 45000 56890"

24. **"vCoordUncM" = verbatim coordinate uncertainty in meters.** If coordinate uncertainty was clearly stated, input this in meters, without the "m" indicating meters.

25. **numPlantsCode = number of plants code.** HJ often used a number code beside taxon names to quickly indicate rough abundance. The key is as follows:

    -   "+" = 1 plants

    -   "1" = 1-5 plants

    -   "2" = 5-25 plants

    -   "3" = 25-50 plants

    -   "4" = 50-75 plants

    -   "5" = 75+ plants

    When entering these codes, enter "+" as 0 and the rest of the numbers as they are stated

26. **"orgQuantity" & "orgQuantityType" = organism quantity and type.** Only use if HJ indicated abundance in some other way other than the number of plants code.

    -   e.g. note about particular species being abundant/ persistant/ dominant/ very few at site --\> orgQuantity = "abundant"/ "persistant" / "dominant", "very few" and "orgQuantityType = **"qualitative"**

    -   e.g. note about there only being one individual --\> orgQuantity = "1", orgQuantityType = "**individuals**"

    -   e.g. note about percent cover --\> orQuantity = "30 percent", orgQuantityType = "percent cover"

27. **"occRemarks" =** occurrence remarks. Anything pertaining to extra information about the observation that hasn't already been entered OR note about other annotations in book for that occurrence such as an asterisk or if the name has been crossed out and replaced with a new one.

    -   e.g. "no usual travel off"

    -   e.g. "dominant"

    -   e.g. "very little, tufts"

    -   e.g. "asterisk next to taxon name"

    -   e.g. "genus name originally X but crossed out"

    -   e.g. "uncollected"

    -   e.g. "mostly Typha at edge"

    -   e.g. "two large beds"

    -   e.g. "varigated"

    -   e.g. "non-flowering"

28. **"phenology"** = if there were any notes about flowering phenology or life stage (either vegetative, flowering, flowering and fruiting, fruiting and flowering, budding, budding and flowering)

    -   e.g. "non-flowering" enter as --\> "vegetative"

    -   e.g. "fl" enter as -\> "flowering"

    -   e.g. "has fruits" or "has seeds" --\> "fruiting"

29. "recordedBy" = people there at time of collection (full names or initials) only enter if there are additional names that Harvey denoted of people with him collecting.

    -   e.g. "PJ" = enter as"Pam Janszen"

30. **"idBy" = identification by**. Only fill out with names if there was a note about someone other than Harvey identifying it.

31. **"dataEntryRemaks" =** any observation with remarks here will be checked over. Write whatever notes are important to completing data entry for that row/ what needs to be helped with.

## When finished entering all data for book:

-   ***Save the final raw data book as both .xlsx and .csv files***

## Important Notes:

1.  **SAVE FREQUENTLY** (by pushing to github or backing up on OSF or Google Drive)

2.  If certain names can't be deciphered or a location/ time can't be attributed to it, **still include as a row in the template,** with a valid **pageNum** an **numPage** entry. It can be removed later (this will help for re-finding things on the page). To help remember what you had a difficult time deciphering, make a note of it in "dataEntryRemarks" and you can additionally attempt to fill out the information and place square brackets around the uncertain parts --\> e.g. [add tophar]?

3.  **DON'T enter any taxon observations with either a collection number or the note "coll no \#" or "coll"** (this indicates a specimen was collected and therefore, we don't want to duplicate data already in herbarium databases)

4.  **AVOID entering repeated observations of same taxa** at same locality, habitat/ sub location and same date

    -   there will be checks to make sure this doesn't happen during data processing, but best to avoid to save time now, if the repetition is really obvious

## **Tips for efficiency**

1.  When you first start a new page or new event (location and date), **count the** number of observations you think you will have. Enter the date and locality info for the first observation and then **copy for the amount of rows you think you will need. The same applies for associated collected occurrences**

2.  When it comes to big chunks where most observations are associated with collections - only write down ones that aren't a collection at that locality - be careful it can sometimes be tricky, but you can write down coordinates for the collected specimen as for the occurrence.

    -   Additionally, you can copy and paste large lists of associated occurrence numbers and taxa names to multiple rows to save time

3.  Using iNaturalist for efficient species type and spelling check

    -   Starting to write a name in the search bar on the explore page and then filling the rest of the name out by looking at the result that pops up

    -   copy and paste this to sheet

# Metadata

-   Abundance codes: from page 1 of the HJ-7 field journal

    -   "+" = 1

    -   "1" = 1-5

    -   "2" = 5-25

    -   "3" = 25-50"

    -   "4" = 50-75

    -   "5" = 75+

-   Codes like Cw, Fd, Md all refer to forest type codes which can be found here: <https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/tree-seed/tree-seed-centre/seed-testing/codes>

# Data Processing

Steps I and II are designed for the user to go through *one journal* at a time. Once completed for all journals, part 3 can be used to to aggregate and formally process the data.

## Setup

Download the repository from Github: <https://github.com/emench/Harvey_Janszen_Legacy_Project>

## Processing step I: data entry checking

1.  Open script **"part1-a_checking.R"**

2.  **Input the journal number** for the data that was entered

3.  Input whether you want to only check high-priority cases (Q \<- "hp") or include "medium" confidence taxon name deciphering flags (Q \<- "all") **(in section 2)**

4.  **Run the script**

5.  To get both options stated in #3, change Q to the other option, and re-run the script

6.  **Find the .csv file** in data \> data_digitization \> occurrence_data \> 2_data_checking

7.  Take the csv file and have it **reviewed by Andrew & Emma to check these flagged observations**

    -   In checking these observations:

        1.  find each occurrence in journal as indicated by archiveID and page numbers

        2.  Fill in uncertain information with best guess

        3.  If still cannot decipher words or are uncertain, make a judgement call as to whether or not to include. If too uncertain about either the taxon name, date observed, or locality, mark this observation with a "Y" or "y" in the toDelete column

        4.  fill the "checkStaus" column with "C" (completed) or "R" (return to) to check progress

    -   once all rows have "C" in the checkStatus column, continue on

8.  Open script **"part1-b_checking.R"**

9.  Under the "LOADING DATA" tab, input the name of the checked file **(filename \<- .. ) and the journal number ( J \<- ... )**

10. Run the script section by section

11. If there is an error generated from section 2, then a row has been missed in the review and should be returned to. Once this is fixed, the data be saved and the script should be re-started.

12. The end result of this step will be a csv file in the "data_cleaning" folder that has been checked for obvious errors. The next step will take care of catching less obvious ones.

## Processing step II: data cleaning

1.  Open script "part2-data-cleaning.R"
2.  Input name of completed data sheet from the previous step in the "3_data_cleaning" folder **(filename \<- ...)** and the **journal number (J\<- ...)**
3.  Open this csv file in another window
4.  Run the script part by part
5.  If an error message pops up after running a particular section, stop, return to the csv sheet in the other window, look for the error and correct it. Use the index values that pop up in the error message to find the location of these errors.
6.  Once corrected, save the sheet, and re-run the script up to an including the section that had previously produced the error message.
7.  Ensure that this error message no longer appears
8.  Repeat these measures until the whole script has been completed
9.  The end result of this script will be a new csv file in the folder "4_clean data" that will be converted to Darwin Core standards in the next script
10. Repeat processing steps I and II for the rest of the journals before continuing on to step 3

## Processing step III: conversion to Darwin Core fields

1.  Open script "part3_template-to-dwc.R"

2.  Run the script to up until step 4 ("Taxonomy Fields").

3.  Follow the instructions in Part 4 to clean taxa names

    -   Upload csv file to <https://www.gbif.org/tools/species-lookup>

    -   Click "match to backbone" button

    -   Click on the "matchType" column label to order these by match type

        -   If match type is yellow or red, click on the neighbouring column "scientificName (editable)"

        -   A list of taxon names will pop up

        -   Select the name that has "accepted" beside it in brackets unless there was a spelling mistake in the verbatim name and you know the verbatim name was refferring to something else. If so, search for that species in the search bar and select the accepted name

        -   If there are multiple accepted names, select the top results (this is often if there are two different authorities accepted)

        -   the match type field should now say "edited"

        -   go back through all pages of entries to check that all rows have match type "exact" or "edited" (grey or green)

        -   select "GENERATE CSV" button in bottom right hand of page

        -   place this downloaded file in data \> data_digitization \> occurrence_data \> occurrence_reference_data \> taxonomy with the name "normalized"

        -   return to script part 3 to load this file in and continue the process

4.  Run the initial part of step 5 (Georeferencing) up until the .csv file is written. Then follow the following instructions for referencing protocol in GEOlocate:

    -   go to GEOlocate batch processor: <https://geo-locate.org/web/WebFileGeoref.aspx>

    -   click "Select File"

    -   upload the .csv file from data \>data_digitization \> occurrence_data \> occurrence_reference_data \> georeferencing \> "localities-to-georef_Xdate.csv"

    -   select 16 - 32 entries / page

    -   click "Options" button \> select "Do Uncertainty" \> "OK" \> "Close" to close this menu

    -   select the "Page Georeference" button \> this might take a moment

    -   select the first row in the table. The map should zoom to one of the pins it has automatically placed on the map

    -   zoom into the map more or zoom out if needed

    -   identify where all of the options are (green and red pins). Green pin = top option, red = alternate possibilities

    -   Editing location: click on the green pin and read the "parse pattern". Then read the locality string for that location (first column in table). Consider...

        -   Does it match? Did it get it wrong?

        -   Did it focus on an extraneous detail in the string rather the main words?

        -   With your knowledge of the geography of the area could you do a better job placing the pin?

        -   If you think the pin is relatively accurate, leave it.

        -   If you think you could do a better job, drag and drop the pin in a new location. Or select another pin (a red pin) that is better matched. The location of this pin can also be edited in a similar manner if needed.

        -   Avoid placing pin in water, and if the automatic result was initially in water, this is a good candidate to edit the location

        -   **Tip:** *manually check locations using google maps or google earth if there is detail about certain lakes that GEOLocate did not catch but you could quickly and roughly approximate (e.g. "Mount Sutil, Galiano" --\> find rough location of Mount Sutil*

    -   Editing Uncertainty. Now look at the circle around it (uncertainty circle). This circle represents the area in which the real coordinate could be inside. Knowing this, consider...

        -   Is it reasonable? e.g. if the locality string says "Galiano Island" does it encompass all of Galiano Island. Similarly is it encompassing much more area than is needed to encompass all of the island?

        -   This is very subjective and open for interpretation. If you are uncertain in your ability to assign uncertainty, leave it as is

        -   If you would like to change it, click on the pin \> select "Edit Uncertainty" \> drag the large arrow in or out to edit the radius of the circle \> when finished click on the pin again

    -   IMPORTANT: IF YOU MAKE ANY EDITS IN LOCATION (you moved the location of a pin or selected a different pin than the one that was in green) OR UNCERTAINTY TO THE PIN, SELECT "CORRECT" before clicking on the next row in the table to save these changes. Otherwise you will have to re-select that row and do everything again since the change in coordinates and uncertainty will not be logged without pressing that button.

    -   repeat for all rows on the page.

    -   when the page is completed, click on the arrow in the bottom right to go to the next page and repeat the process. The changes made to the previous page should still be saved as you go.

    -   once all localities have been georeferenced, export the file by..

        -   click the "Export" button at the bottom of the screen

        -   select:

            -   delimited text: "CSV"

            -   "exclude all polygons"

            -   "ok"

        -   rename the exported file to "geoLocate_YYYY_MM_DD"

        -   place the exported file in data \> data_digitization \> occurrence_data \> occurrence_reference_data \> georeferencing

5.  Return to the script and run the rest of section 5 starting at the "loading georeferenced occurrences" step.

6.  A map should appear with the occurrences. If some coordinates seem off, these can be searched by referencing the coordinates on the map and matching to rows by either manually searching data or statements such as...

    > ``` r
    >  occ_data[which(occ_data$decimalLatitude > 50 & occ_data$decimalLongitude < -124.3)]
    > ```

-   The rows matching these criteria should appear, and can be checked.

-   Manually change the coordinates in the spreadsheet and re-run the whole script until this point to fix any errors.

7.  Run the rest of the script
8.  The output will be a CSV file with all of the digitized occurrences in the "occurrence_data" folder labelled with the date of processing
